// Application tables. Auth tables (user, session, account, verification) are generated by the Better Auth CLI.
import { index, integer, jsonb, pgTable, real, text, timestamp } from "drizzle-orm/pg-core";
import type { ProjectSettings, StoryPlan } from "../lib/engine/types";
import { user } from "./auth-schema";

export const projects = pgTable(
  "projects",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull().default("Untitled story"),
    story: text("story").notNull().default(""),
    duration: integer("duration").notNull().default(30),
    settings: jsonb("settings").$type<ProjectSettings>().notNull(),
    plan: jsonb("plan").$type<StoryPlan | null>(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index("projects_user_updated_idx").on(t.userId, t.updatedAt)],
);

export const renders = pgTable(
  "renders",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    status: text("status", { enum: ["queued", "rendering", "done", "failed"] }).notNull().default("queued"),
    progress: real("progress").notNull().default(0),
    error: text("error"),
    /** Storage keys of the finished MP4 and its poster frame. */
    videoKey: text("video_key"),
    posterKey: text("poster_key"),
    duration: real("duration"),
    size: integer("size"),
    /** Snapshot of plan + settings at request time, so later edits don't change a queued render. */
    input: jsonb("input").$type<{ plan: StoryPlan; settings: ProjectSettings; title: string }>().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index("renders_project_created_idx").on(t.projectId, t.createdAt), index("renders_user_status_idx").on(t.userId, t.status)],
);

export type ProjectRow = typeof projects.$inferSelect;
export type RenderRow = typeof renders.$inferSelect;
